Fundamental Python

In [2]:
# queremos entender esto
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)

print (quicksort([3,6,8,10,1,2,1]))

[1, 1, 2, 3, 6, 8, 10]


Numbers:

Integers and floats work as you would expect from other languages

In [5]:
x = 3
print (x)
type(x)

3


int

In [6]:
print (x + 1)   # Addition;
print (x - 1)   # Subtraction;
print (x * 2)   # Multiplication;
print (x ** 2)  # Exponentiation;

4
2
6
9


In [8]:
x += 1
print(x)  # Prints "4"
x *= 2
print (x ) # Prints "8"

4
8


Booleans

In [9]:
t, f = True, False
print (type(t)) # Prints "<type 'bool'>"

<class 'bool'>


In [10]:
print (t and f) # Logical AND;
print (t or f)  # Logical OR;
print (not t )  # Logical NOT;
print (t != f)  # Logical XOR;

False
True
False
True


Strings

In [11]:
hello = 'hello'   # String literals can use single quotes
world = "world"   # or double quotes; it does not matter.
print (hello, len(hello))

hello 5


In [14]:
s = "hello"
print (s.capitalize())  # Capitalize a string; prints "Hello"
print (s.upper())       # Convert a string to uppercase; prints "HELLO"
print (s.rjust(7) )     # Right-justify a string, padding with spaces; prints "  hello"
print (s.center(7))     # Center a string, padding with spaces; prints " hello "
print (s.replace('l', '(ell)'))  # Replace all instances of one substring with another;
                               # prints "he(ell)(ell)o"
print ('  world '.strip())  # Strip leading and trailing whitespace; prints "world"

Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world


List

In [15]:
xs = [3, 1, 2]   # Create a list
print (xs, xs[2])
print (xs[-1])     # Negative indices count from the end of the list; prints "2"

[3, 1, 2] 2
2


In [16]:
xs[2] = 'foo'    # Lists can contain elements of different types
print (xs)

[3, 1, 'foo']


In [17]:

xs.append('bar') # Add a new element to the end of the list
print (xs)

[3, 1, 'foo', 'bar']


Slicing

In [22]:
nums =[0, 1, 2, 3, 4]
print (nums )        # Prints "[0, 1, 2, 3, 4]"
print (nums[2:4])    # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print (nums[2:] )    # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print (nums[:2] )    # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print (nums[:]  )    # Get a slice of the whole list; prints ["0, 1, 2, 3, 4]"
print (nums[:-1] )   # Slice indices can be negative; prints ["0, 1, 2, 3]"
nums[2:4] = [8, 9] # Assign a new sublist to a slice
print( nums )        # Prints "[0, 1, 8, 9, 4]"

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


Loops

In [26]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print (animal)

cat
dog
monkey


In [27]:
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print ('#%d: %s' % (idx + 1, animal))

#1: cat
#2: dog
#3: monkey


List comprehensions
transformar un tipo de dato en otro

In [28]:
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
print (squares)

[0, 1, 4, 9, 16]


In [29]:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print (squares)

[0, 1, 4, 9, 16]


In [30]:
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print (even_squares)

[0, 4, 16]


Dictionaries
A dictionary stores (key, value) pairs. MongoDB

In [31]:
d = {'cat': 'cute', 'dog': 'furry'}  # Create a new dictionary with some data
print (d['cat'] )      # Get an entry from a dictionary; prints "cute"
print ('cat' in d )    # Check if a dictionary has a given key; prints "True

cute
True


In [34]:
d['fish'] = 'wet'    # Set an entry in a dictionary
print (d['fish'],'and',d )     # Prints "wet"

wet and {'cat': 'cute', 'dog': 'furry', 'fish': 'wet'}


In [35]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal in d:
    legs = d[animal]
    print ('A %s has %d legs' % (animal, legs))

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


In [36]:
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals): ## enumero 
    print( '#%d: %s' % (idx + 1, animal))

#1: dog
#2: fish
#3: cat


Tuples: A tuple is an (immutable) ordered list of values. A tuple is in many ways similar to a list;

In [40]:
d = {(x, x + 1): x for x in range(10)}  # Create a dictionary with tuple keys
t = (5, 6)       # Create a tuple
print (type(t))
print (d[t]    )   
print (d[(1, 2)])
print (d)
print (t)

<class 'tuple'>
5
1
{(0, 1): 0, (1, 2): 1, (2, 3): 2, (3, 4): 3, (4, 5): 4, (5, 6): 5, (6, 7): 6, (7, 8): 7, (8, 9): 8, (9, 10): 9}
(5, 6)


Functions

In [44]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'
## pruebo
for x in [-1, 0, 1]:
    print (sign(x))

negative
zero
positive


In [43]:
print (sign (-1)) ## me perdi ... 

negative


Arrays: no olvidar importar numpy

In [47]:
import numpy as np
a = np.array([1, 2, 3])  # Create a rank 1 array
print (type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 # Change an element of the array
print( a)

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [48]:
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print (b)

[[1 2 3]
 [4 5 6]]
